twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['form/form_theme.html.twig']

    globals:
        locales: '%locales%'
        site_name: '%env(SITE_NAME)%'
        site_link: '%env(SITE_LINK)%'
