twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['form/form_theme.html.twig']

    globals:
        _locales: '%locales%'
        _site_name: '%env(SITE_NAME)%'
        _site_link: '%env(SITE_LINK)%'
        _email: '%env(MAILER_ADDRESS)%'
        _notifications: '@App\Service\Notification\NotificationService'
